#!/bin/bash

timestamp=`date +%Y-%m-%d_%H%M%S`
echo "Program started at $timestamp"

o=../output
r=$o/raw
p=$r/positive-cases
t=$r/tests
m=$o/misc
mkdir -p $p $t $m

fca1File=$fca1/$f
fca2File=$fca2/$f
fca3File=$fca3/$f


echo "Making CSVs from case-line data."
od=$o/datawrapper
Rscript process-case-line-data.r $p $od

echo "======"

echo "Making CSVs related to coronavirus deaths."
Rscript processors/deaths-by-date.r $p $od

# echo "Making data files for Google Sheets for other reporters"
# Rscript cases-reported-by-county-and-date.r $t $m