#!/bin/bash

timestamp=`date +%Y-%m-%d_%H%M%S`
echo "Program started at $timestamp"

o=output
r=$o/raw
p=$r/positive-cases
t=$r/tests
h=$r/hospital-bed-data
i=$r/indicators
fca1=$r/weekly-health-metrics
fca2=$r/deaths-in-care-facilities
fca3=$r/long-term-care-cases
m=$o/misc
mkdir -p $p $t $h $i $fca1 $fca2 $fca3 $m

f=FL-$timestamp.csv
caseLineFile=$p/$f
testsByCountyFile=$t/$f
hospitalBedFile=$h/$f
indicatorsFile=$i/$f
fca1File=$fca1/$f
fca2File=$fca2/$f
fca3File=$fca3/$f

echo "Making data files for most charts."
od=$o/datawrapper
Rscript make-datafiles-for-charts.r $caseLineFile $testsByCountyFile $od $ret1 $ret2 $timestamp $t

echo "Making data files for coronavirus death charts."
Rscript deaths-by-date.r $p $od

echo "Making data files for Google Sheets for other reporters"
Rscript cases-reported-by-county-and-date.r $t $m

echo "Updating charts"
Rscript update-charts.r $timestamp $od/county.csv $od/south-fl.csv $ret1 $ret2
